# Generated by Django 3.2.9 on 2021-11-25 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_telefontecliente_clientes_telefonecliente'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientes',
            name='Entrega',
            field=models.CharField(default='SOME STRING', max_length=80),
        ),
        migrations.AddField(
            model_name='clientes',
            name='formaPagamento',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='clientes',
            name='marcaAparelho',
            field=models.CharField(default='SOME STRING', max_length=50),
        ),
        migrations.AddField(
            model_name='clientes',
            name='valorServico',
            field=models.FloatField(default='0'),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='eletrodomestico',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='enderecoCliente',
            field=models.CharField(default='SOME STRING', max_length=80),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nomeCliente',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefoneCliente',
            field=models.CharField(default='SOME STRING', max_length=30),
        ),
    ]
