# Generated by Django 3.2.9 on 2021-11-25 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20211124_2108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientes',
            name='Entrega',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='eletrodomestico',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='enderecoCliente',
            field=models.CharField(default='', max_length=80),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='formaPagamento',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='marcaAparelho',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='nomeCliente',
            field=models.CharField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='clientes',
            name='telefoneCliente',
            field=models.CharField(default='', max_length=30),
        ),
    ]
